nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-3.2.1.cjs

packageExtensions:
  "@docsearch/react@*":
    peerDependencies:
      "@algolia/client-search": ^4.9.1
  "@docusaurus/core@*":
    dependencies:
      typescript: "*"
  "@docusaurus/preset-classic@*":
    peerDependencies:
      "@algolia/client-search": ^4.9.1
  "@docusaurus/theme-search-algolia@*":
    peerDependencies:
      "@algolia/client-search": ^4.9.1
  "@docusaurus/types@*":
    peerDependencies:
      react: ^16.8.4 || ^17.0.0
      react-dom: ^16.8.4 || ^17.0.0
  react-dev-utils@*:
    peerDependencies:
      typescript: "*"
      webpack: "*"
